# Generated by Django 3.2.6 on 2021-09-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='user',
        ),
    ]
