# Generated by Django 3.2.6 on 2021-09-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0002_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
