# Generated by Django 3.2.6 on 2021-10-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0004_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
