# Generated by Django 3.2.6 on 2021-09-13 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0004_alter_exerciseset_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pose.set'),
        ),
    ]
