# Generated by Django 3.2.6 on 2021-09-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0005_alter_exerciseset_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pose.set'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise', to='pose.exercise'),
        ),
    ]
