# Generated by Django 3.2.6 on 2021-10-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0005_todo_created_at'),
        ('pose', '0007_alter_customuser_profile_img'),
    ]

    operations = [
    ]
