# Generated by Django 3.2.6 on 2021-10-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0008_merge_20211016_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
