# Generated by Django 3.2.6 on 2021-10-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0008_merge_20211030_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='set_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pose.exerciseset'),
        ),
    ]
