# Generated by Django 3.2.6 on 2021-11-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0009_alter_exerciselog_set_exercise'),
        ('pose', '0009_remove_todo_description'),
    ]

    operations = [
    ]
