# Generated by Django 3.2.5 on 2021-08-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_exerciseset_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='user_count',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
    ]
